service: dw-polling
runtime: nodejs
env: flexible

# update with Redis instance network name
network:
  name: default

# update with Redis instance network name
beta_settings:
  cloud_sql_instance: dwatch-184008:us-east1:dashwatch-polling>=5432

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.25
  disk_size_gb: 10 