service: dw-polling
runtime: nodejs10
env: standard

# update with Redis instance network name
network:
    name: default

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 2

handlers:
- url: /.*
  script: auto
  secure: always