service: dash-watch-beta
runtime: nodejs10
env: standard

# update with Redis instance network name
vpc_access_connector:
  name: "projects/dwatch-184008/locations/us-central1/connectors/dashwatchbeta-connector"

instance_class: B1
basic_scaling:
  idle_timeout: 5m
  max_instances: 1

handlers:
- url: /.*
  script: auto
  secure: always
