service: dw-dif2020
runtime: nodejs10
env: standard

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 2

handlers:
- url: /.*
  script: auto
  secure: always